// ALL SITE CONTENT lives here. Each collection is a list of rows; the field keys (f1, f2 … img, n1) are the ones the
// sections read (they mirror the Framer CMS bridge). n1 = sort order. Swap this file for a CMS / database later:
// only `useCMS` in lib/rw.tsx reads it.

export type CmsRow = Record<string, string>

// site — the one-row collection of agency-wide facts
// f1 name · f2 role · f3 tagline · f4 email · f5 phone · f6 booking link · f7 city · f8 time zone
// f9 rating · f10 reviews count · f11 socials (Label:url, …) · f12 announcement · f13 clients count
const site: CmsRow[] = [
    {
        slug: "site",
        f1: "Reachwise",
        f2: "Digital marketing agency",
        f3: "SEO, social media and paid ads that bring the right people to your door.",
        f4: "hello@reachwise.agency",
        f5: "+1 (212) 555-0186",
        f6: "/contact",
        f7: "New York",
        f8: "America/New_York",
        f9: "4.9",
        f10: "126",
        f11: "Instagram:https://instagram.com,TikTok:https://tiktok.com,LinkedIn:https://linkedin.com,X:https://x.com",
        f12: "Now booking Q4 · 3 spots left",
        f13: "140+",
        n1: "1",
    },
]

// services — f1 title · f2 one-liner · f3 body · f4 price · f5 includes (;) · f6 mini-UI kind (seo|social|ads|content|web|brand) · f7 stat
const services: CmsRow[] = [
    {
        slug: "seo",
        f1: "SEO",
        f2: "Rank for the searches that buy.",
        f3: "Technical fixes, content and links that move you up the page for the words your customers type.",
        f4: "$1,500/mo",
        f5: "Technical audit;Keyword map;4 articles a month;Link building;Monthly ranking report",
        f6: "seo",
        f7: "#1 for 212 keywords",
        n1: "1",
    },
    {
        slug: "social-media",
        f1: "Social media",
        f2: "Posts people stop for.",
        f3: "Strategy, shooting, editing and community management on Instagram, TikTok and LinkedIn.",
        f4: "$1,800/mo",
        f5: "12 posts + 8 reels a month;Content calendar;Community replies;Monthly report",
        f6: "social",
        f7: "48k average reel views",
        n1: "2",
    },
    {
        slug: "paid-ads",
        f1: "Paid ads",
        f2: "Every dollar tracked to a sale.",
        f3: "Meta, Google and TikTok campaigns built around your margins, tested weekly and reported in revenue.",
        f4: "$1,200/mo + ad spend",
        f5: "Account setup;Creative testing;Weekly optimisation;Revenue dashboard",
        f6: "ads",
        f7: "6.2× return on ad spend",
        n1: "3",
    },
    {
        slug: "content",
        f1: "Content",
        f2: "Articles, videos and emails that sell.",
        f3: "Blog posts, newsletters and short videos written for search and for people.",
        f4: "$1,400/mo",
        f5: "Editorial plan;4 long-form articles;2 newsletters;Repurposed clips",
        f6: "content",
        f7: "3.4× more leads from blog",
        n1: "4",
    },
    {
        slug: "web-design",
        f1: "Web design",
        f2: "Sites that turn visits into calls.",
        f3: "Fast Framer and Webflow websites with landing pages built to convert your traffic.",
        f4: "$4,500 once",
        f5: "Wireframes;Design + build;CMS setup;Speed + SEO basics",
        f6: "web",
        f7: "+64% conversion rate",
        n1: "5",
    },
    {
        slug: "branding",
        f1: "Branding",
        f2: "A brand people remember.",
        f3: "Naming, logo, colours and a voice that makes your ads and posts look like one company.",
        f4: "$3,800 once",
        f5: "Brand workshop;Logo + identity;Brand guidelines;Social templates",
        f6: "brand",
        f7: "2 weeks to launch",
        n1: "6",
    },
]

// work (case studies) — f1 client · f2 headline · f3 industry · f4 services (;) · f5 metric label · f6 before · f7 after
// f8 unit suffix · f9 year · f10 summary · img cover
const work: CmsRow[] = [
    {
        slug: "northside-dental",
        f1: "Northside Dental",
        f2: "From page 4 to the top 3 for “dentist near me”",
        f3: "Dental clinic",
        f4: "SEO;Content",
        f5: "Organic visits a month",
        f6: "4,200",
        f7: "38,900",
        f8: "",
        f9: "2025",
        f10: "A local SEO rebuild: 60 location pages, 180 reviews and a content plan for every treatment.",
        img: "/images/iQ0lX69C3YgeRjqffxWadnnAmnc.webp",
        n1: "1",
    },
    {
        slug: "kinfolk-coffee",
        f1: "Kinfolk Coffee",
        f2: "A coffee brand people film for us",
        f3: "Food & drink",
        f4: "Social media;Content",
        f5: "Instagram followers",
        f6: "8,100",
        f7: "96,400",
        f8: "",
        f9: "2025",
        f10: "Three reels a week shot in the roasteries turned a local brand into a national one.",
        img: "/images/myjp4zr3op66cJhewFtasNpY5I.webp",
        n1: "2",
    },
    {
        slug: "fitloop",
        f1: "Fitloop",
        f2: "Paid ads that pay for themselves in 11 days",
        f3: "Fitness app",
        f4: "Paid ads",
        f5: "Return on ad spend",
        f6: "1.4",
        f7: "6.2",
        f8: "×",
        f9: "2025",
        f10: "We rebuilt the Meta account around creative testing and cut the cost per trial by 58%.",
        img: "/images/hd4rblq8DW7sPIt8FWcRq1HdmQ0.webp",
        n1: "3",
    },
    {
        slug: "haven-realty",
        f1: "Haven Realty",
        f2: "A pipeline of sellers, not just clicks",
        f3: "Real estate",
        f4: "Paid ads;Web design",
        f5: "Seller leads a month",
        f6: "14",
        f7: "122",
        f8: "",
        f9: "2024",
        f10: "A new site with valuation landing pages and Google campaigns for every neighbourhood.",
        img: "/images/zEqvjQAlVPs2PE6oz2TsexQ8TA.webp",
        n1: "4",
    },
    {
        slug: "lumen-skin",
        f1: "Lumen Skin",
        f2: "A skincare launch that sold out twice",
        f3: "Beauty",
        f4: "Social media;Branding",
        f5: "Launch-week revenue",
        f6: "$18k",
        f7: "$142k",
        f8: "",
        f9: "2024",
        f10: "Brand, creators and a TikTok launch plan built in six weeks.",
        img: "/images/QSuLrUGcfrrneXqjDG4ZKyC91Gk.webp",
        n1: "5",
    },
    {
        slug: "orbit-legal",
        f1: "Orbit Legal",
        f2: "Thought leadership that books consultations",
        f3: "Law firm",
        f4: "Content;SEO",
        f5: "Consultations a month",
        f6: "9",
        f7: "57",
        f8: "",
        f9: "2024",
        f10: "Weekly LinkedIn posts and long-form guides that rank and get shared by clients.",
        img: "/images/csWXqRpXZMLSqxx74oKZj5QkJw.webp",
        n1: "6",
    },
]

// team — f1 name · f2 role · f3 bio · f4 focus · f5 LinkedIn · img portrait
const team: CmsRow[] = [
    {
        slug: "maya-chen",
        f1: "Maya Chen",
        f2: "Founder & strategy lead",
        f3: "Ten years running growth for consumer brands before starting Reachwise.",
        f4: "Strategy",
        f5: "https://linkedin.com",
        img: "/images/HxGAwVNM9ZaaBu6N5yRyWcYxYQM.webp",
        n1: "1",
    },
    {
        slug: "jordan-reyes",
        f1: "Jordan Reyes",
        f2: "Head of SEO",
        f3: "Has taken 40+ local businesses to the top three on Google.",
        f4: "SEO",
        f5: "https://linkedin.com",
        img: "/images/JXNHKwjRlDqIdZuxCrbzCaz9Td8.webp",
        n1: "2",
    },
    {
        slug: "amara-okafor",
        f1: "Amara Okafor",
        f2: "Social media director",
        f3: "Runs the content team and every client's reel calendar.",
        f4: "Social",
        f5: "https://linkedin.com",
        img: "/images/371lVaDSMdqEsHSlTLGeKl7650.webp",
        n1: "3",
    },
    {
        slug: "liam-novak",
        f1: "Liam Novak",
        f2: "Paid ads lead",
        f3: "Manages $4M a year in Meta and Google spend.",
        f4: "Paid ads",
        f5: "https://linkedin.com",
        img: "/images/NmkpUVq1OjshWo3MRYHXbDUFJGU.webp",
        n1: "4",
    },
    {
        slug: "sofia-marin",
        f1: "Sofia Marín",
        f2: "Content lead",
        f3: "Former magazine editor who writes for search and for people.",
        f4: "Content",
        f5: "https://linkedin.com",
        img: "/images/wTEJQWR3N9EVhTU88mXAPHBq5g4.webp",
        n1: "5",
    },
    {
        slug: "theo-park",
        f1: "Theo Park",
        f2: "Design lead",
        f3: "Designs the sites, brands and ads our clients launch with.",
        f4: "Design",
        f5: "https://linkedin.com",
        img: "/images/LBJSHBzWF5iwJGgfJgtazdyk8.webp",
        n1: "6",
    },
]

// reviews — f1 name · f2 role · f3 company · f4 quote · f5 result chip · f6 stars · img avatar
const reviews: CmsRow[] = [
    {
        slug: "r1",
        f1: "Dr. Hannah Lee",
        f2: "Owner",
        f3: "Northside Dental",
        f4: "We went from four new patients a week to four a day. They report every number and explain what they changed.",
        f5: "+826% organic visits",
        f6: "5",
        img: "/images/YqwmM7lRs3vsXpr2grgwzyJ62LE.webp",
        n1: "1",
    },
    {
        slug: "r2",
        f1: "Marcus Bell",
        f2: "Co-founder",
        f3: "Kinfolk Coffee",
        f4: "Our reels finally look like us. The team shoots, edits and posts, and we just approve.",
        f5: "96k followers",
        f6: "5",
        img: "/images/YYdQD4OSWKjNOGVWs9tCxMobw8I.webp",
        n1: "2",
    },
    {
        slug: "r3",
        f1: "Priya Nair",
        f2: "Growth lead",
        f3: "Fitloop",
        f4: "The first agency that talks about our margins, not clicks. Ads paid back in eleven days.",
        f5: "6.2× ROAS",
        f6: "5",
        img: "/images/RqmMNLZRFBKyGJxcMWBx21DI85Q.webp",
        n1: "3",
    },
    {
        slug: "r4",
        f1: "Tom Alvarez",
        f2: "Broker",
        f3: "Haven Realty",
        f4: "Seller leads every week from our own site. We stopped buying leads from portals.",
        f5: "122 leads/mo",
        f6: "5",
        img: "/images/gv5mT4bQ8T1n4dyt3U0G2Gfwldw.webp",
        n1: "4",
    },
    {
        slug: "r5",
        f1: "Elena Rossi",
        f2: "Founder",
        f3: "Lumen Skin",
        f4: "They built the brand and the launch. We sold out twice in the first month.",
        f5: "$142k launch week",
        f6: "5",
        img: "/images/FkGV79fUruxxZYYaCa5EOB8RME.webp",
        n1: "5",
    },
    {
        slug: "r6",
        f1: "David Kim",
        f2: "Partner",
        f3: "Orbit Legal",
        f4: "Clients now mention our LinkedIn posts in the first call. That never happened before.",
        f5: "57 consults/mo",
        f6: "5",
        img: "/images/x1XkAfPNF95aDnEhP091G8c03KY.webp",
        n1: "6",
    },
]

// plans — f1 name · f2 monthly price · f3 quarterly price · f4 tagline · f5 includes (;) · f6 button · f7 featured (yes)
const plans: CmsRow[] = [
    {
        slug: "starter",
        f1: "Starter",
        f2: "1900",
        f3: "1700",
        f4: "One channel, done properly.",
        f5: "One channel (SEO, social or ads);Monthly strategy call;Monthly report;Email support",
        f6: "Start with Starter",
        f7: "",
        n1: "1",
    },
    {
        slug: "growth",
        f1: "Growth",
        f2: "3900",
        f3: "3500",
        f4: "Two channels working together.",
        f5: "Two channels;Weekly check-in;Live dashboard;Content shoots;Slack support",
        f6: "Choose Growth",
        f7: "yes",
        n1: "2",
    },
    {
        slug: "scale",
        f1: "Scale",
        f2: "7500",
        f3: "6750",
        f4: "The full team on your brand.",
        f5: "SEO + social + paid ads;Dedicated strategist;Creative team;Landing pages;Priority support",
        f6: "Talk to us",
        f7: "",
        n1: "3",
    },
]

// faq — f1 question · f2 answer · f3 group
const faq: CmsRow[] = [
    {
        slug: "f1",
        f1: "How long until we see results?",
        f2: "Paid ads show results in the first two weeks. Social grows month by month. SEO usually moves in 3 to 6 months, and we show progress in every report.",
        f3: "General",
        n1: "1",
    },
    {
        slug: "f2",
        f1: "Do we have to sign a long contract?",
        f2: "No. Retainers run month to month with 30 days notice. Most clients stay because the numbers keep going up.",
        f3: "General",
        n1: "2",
    },
    {
        slug: "f3",
        f1: "Is ad spend included in the price?",
        f2: "No. Ad spend is paid straight to Meta, Google or TikTok from your own account, so you always own the data.",
        f3: "Pricing",
        n1: "3",
    },
    {
        slug: "f4",
        f1: "Which industries do you work with?",
        f2: "Local services, e-commerce, apps and professional firms. We say no when we can't move the numbers.",
        f3: "General",
        n1: "4",
    },
    {
        slug: "f5",
        f1: "Who creates the content?",
        f2: "Our in-house team writes, shoots and edits. You approve everything before it goes live.",
        f3: "Process",
        n1: "5",
    },
    {
        slug: "f6",
        f1: "How do you report results?",
        f2: "A live dashboard plus a monthly call where we walk through what worked, what didn't and what we'll change.",
        f3: "Process",
        n1: "6",
    },
    {
        slug: "f7",
        f1: "Can you work with our in-house team?",
        f2: "Yes. We often run one channel while your team handles the rest, and share every file and login.",
        f3: "Process",
        n1: "7",
    },
    {
        slug: "f8",
        f1: "What happens on the first call?",
        f2: "A free 30-minute audit of your site, socials and ads, and a plan you can keep even if we don't work together.",
        f3: "General",
        n1: "8",
    },
]

// posts (blog) — f1 title · f2 category · f3 date · f4 read time · f5 excerpt · f6 body · img cover
const posts: CmsRow[] = [
    {
        slug: "local-seo-2026",
        f1: "Local SEO in 2026: what still moves the map pack",
        f2: "SEO",
        f3: "Sep 18, 2026",
        f4: "7 min",
        f5: "Reviews, pages and links: the three things that still decide who shows up first near you.",
        f6: "Local search still comes down to three things...",
        img: "/images/pHOBF7LHy4BbDr36flWPxPYRixo.webp",
        n1: "1",
    },
    {
        slug: "reels-that-sell",
        f1: "Reels that sell: the 3-second rule we use for every client",
        f2: "Social media",
        f3: "Sep 04, 2026",
        f4: "5 min",
        f5: "Why the first three seconds decide whether anyone sees the other twenty-seven.",
        f6: "Every reel we make starts with one question...",
        img: "/images/87wKn5rFSjsCMUA9My0OUYJ4dM.webp",
        n1: "2",
    },
    {
        slug: "roas-is-not-profit",
        f1: "ROAS is not profit: how we report paid ads",
        f2: "Paid ads",
        f3: "Aug 21, 2026",
        f4: "6 min",
        f5: "A 6× return can still lose money. Here is the number we report instead.",
        f6: "Return on ad spend is the number everyone quotes...",
        img: "/images/NtmyAnUBIcfQXkgdgwQGB2dIVY.webp",
        n1: "3",
    },
    {
        slug: "content-calendar",
        f1: "The one-page content calendar we give every client",
        f2: "Content",
        f3: "Aug 07, 2026",
        f4: "4 min",
        f5: "A plan your team will actually follow, with a template you can copy.",
        f6: "Most content calendars die in week two...",
        img: "/images/5NYoUMxcMZ7W73IVonEHOzeu5ls.webp",
        n1: "4",
    },
    {
        slug: "landing-pages",
        f1: "Five landing page fixes that doubled conversions",
        f2: "Web design",
        f3: "Jul 24, 2026",
        f4: "6 min",
        f5: "Small changes to headlines, forms and proof that paid for themselves in a week.",
        f6: "Before you spend more on ads...",
        img: "/images/2JG0A1F7J2tdiUI5Y6YXMfSc.webp",
        n1: "5",
    },
    {
        slug: "agency-or-in-house",
        f1: "Agency or in-house? An honest comparison",
        f2: "Strategy",
        f3: "Jul 10, 2026",
        f4: "8 min",
        f5: "What it really costs to hire a marketing team, and when an agency makes more sense.",
        f6: "It depends on three numbers...",
        img: "/images/P2vtvmpcIxWwVrN78FW1tzLdNs.webp",
        n1: "6",
    },
]

export const CONTENT: Record<string, CmsRow[]> = {
    site,
    services,
    work,
    team,
    reviews,
    plans,
    faq,
    posts,
}
