// ALL SITE CONTENT lives here. Each collection is a list of rows; the field keys (f1, f2 … img, n1) are the ones the
// sections read (they mirror the Framer CMS bridge). n1 = sort order. Swap this file for a CMS / database later:
// only `useCMS` in lib/rw.tsx reads it.

export type CmsRow = Record<string, string>

// site — the one-row collection of agency-wide facts
// f1 name · f2 role · f3 tagline · f4 email · f5 phone · f6 booking link · f7 city · f8 time zone
// f9 rating · f10 reviews count · f11 socials (Label:url, …) · f12 announcement · f13 clients count
const site: CmsRow[] = [
    {
        slug: "site",
        f1: "BOS Media Labs",
        f2: "Digital marketing agency",
        f3: "Short-form content, paid ads, AI systems and websites that bring the right people to your door.",
        f4: "hello@bosmedialabs.com",
        f5: "+1 (212) 555-0186",
        f6: "/contact",
        f7: "New York",
        f8: "America/New_York",
        f9: "4.9",
        f10: "126",
        f11: "Instagram:https://instagram.com,TikTok:https://tiktok.com,LinkedIn:https://linkedin.com,X:https://x.com",
        f12: "Now booking Q4 · 3 spots left",
        f13: "140+",
        n1: "1",
    },
]

// services — f1 title · f2 one-liner · f3 body · f4 price (empty = hidden) · f5 includes (;) · f6 mini-UI kind (seo|social|ads|content|web|brand) · f7 stat
const services: CmsRow[] = [
    {
        slug: "seo",
        f1: "SEO",
        f2: "Rank for the searches that buy.",
        f3: "Technical fixes, content and links that move you up the page for the words your customers type.",
        f4: "",
        f5: "Technical audit;Keyword map;4 articles a month;Link building;Monthly ranking report",
        f6: "seo",
        f7: "#1 for 212 keywords",
        n1: "1",
    },
    {
        slug: "social-media",
        f1: "Social media",
        f2: "Posts people stop for.",
        f3: "Strategy, shooting, editing and community management on Instagram, TikTok and LinkedIn.",
        f4: "",
        f5: "12 posts + 8 reels a month;Content calendar;Community replies;Monthly report",
        f6: "social",
        f7: "25M+ organic views for Ring Magazine",
        n1: "2",
    },
    {
        slug: "paid-ads",
        f1: "Paid ads",
        f2: "Every dollar tracked to a sale.",
        f3: "Meta, Google and TikTok campaigns built around your margins, tested weekly and reported in revenue.",
        f4: "",
        f5: "Account setup;Creative testing;Weekly optimisation;Revenue dashboard",
        f6: "ads",
        f7: "8× ROAS on Google Ads",
        n1: "3",
    },
    {
        slug: "content",
        f1: "Content",
        f2: "Articles, videos and emails that sell.",
        f3: "Blog posts, newsletters and short videos written for search and for people.",
        f4: "",
        f5: "Editorial plan;4 long-form articles;2 newsletters;Repurposed clips",
        f6: "content",
        f7: "3.4× more leads from blog",
        n1: "4",
    },
    {
        slug: "web-design",
        f1: "Web design",
        f2: "Sites that turn visits into calls.",
        f3: "Fast Framer and Webflow websites with landing pages built to convert your traffic.",
        f4: "",
        f5: "Wireframes;Design + build;CMS setup;Speed + SEO basics",
        f6: "web",
        f7: "+64% conversion rate",
        n1: "5",
    },
    {
        slug: "branding",
        f1: "Branding",
        f2: "A brand people remember.",
        f3: "Naming, logo, colours and a voice that makes your ads and posts look like one company.",
        f4: "",
        f5: "Brand workshop;Logo + identity;Brand guidelines;Social templates",
        f6: "brand",
        f7: "2 weeks to launch",
        n1: "6",
    },
]

// work (case studies) — f1 client · f2 headline · f3 industry · f4 services (;) · f5 metric label · f6 before · f7 after
// f8 unit suffix · f9 year · f10 summary · img cover
const work: CmsRow[] = [
    {
        slug: "ring-magazine",
        f1: "Ring Magazine",
        f2: "A 5-page fan network that pulled 25M+ organic views",
        f3: "Media · Boxing",
        f4: "Clipping;Short-form content",
        f5: "Organic views",
        f6: "0",
        f7: "25M+",
        f8: "",
        f9: "Since Dec 2025",
        f10: "Boxing's most iconic brand had a huge content library but no short-form presence. We built a 5-page fan network: 770+ clips posted, a 2.5M-view top clip and a 2× engagement rate.",
        img: "/images/cover-ring-magazine.webp",
        n1: "1",
    },
    {
        slug: "aps-home-security",
        f1: "APS Home Security",
        f2: "An AI assistant that handles homeowner requests, plus a new website",
        f3: "Home security · Los Angeles",
        f4: "AI systems;Web design",
        f5: "Request types automated",
        f6: "0",
        f7: "3",
        f8: "",
        f9: "2025",
        f10: "A custom voice and chat assistant for APS homeowners: it books technicians, schedules vacation watch and takes burglary-watch requests, with automatic follow-ups and an admin dashboard. We also built their website.",
        img: "/images/cover-aps-home-security.webp",
        n1: "2",
    },
    {
        slug: "body-suite-spa",
        f1: "Body Suite Spa",
        f2: "Paid ads that returned 8× on Google and 7× on Facebook",
        f3: "Health & wellness",
        f4: "Google Ads;Facebook Ads;CRM & automation",
        f5: "Return on ad spend · Google Ads",
        f6: "—",
        f7: "8×",
        f8: "",
        f9: "2024–25",
        f10: "We ran marketing operations for the spa: Google and Facebook campaigns plus the CRM and automations behind them, reaching 8× ROAS on Google Ads and 7× on Facebook Ads.",
        img: "/images/cover-body-suite-spa.webp",
        n1: "3",
    },
]

// team — f1 name · f2 role · f3 bio · f4 focus · f5 LinkedIn · img portrait
const team: CmsRow[] = [
    {
        slug: "maya-chen",
        f1: "Maya Chen",
        f2: "Founder & strategy lead",
        f3: "Ten years running growth for consumer brands before starting BOS Media Labs.",
        f4: "Strategy",
        f5: "https://linkedin.com",
        img: "https://framerusercontent.com/images/HxGAwVNM9ZaaBu6N5yRyWcYxYQM.webp",
        n1: "1",
    },
    {
        slug: "jordan-reyes",
        f1: "Jordan Reyes",
        f2: "Head of SEO",
        f3: "Has taken 40+ local businesses to the top three on Google.",
        f4: "SEO",
        f5: "https://linkedin.com",
        img: "https://framerusercontent.com/images/JXNHKwjRlDqIdZuxCrbzCaz9Td8.webp",
        n1: "2",
    },
    {
        slug: "amara-okafor",
        f1: "Amara Okafor",
        f2: "Social media director",
        f3: "Runs the content team and every client's reel calendar.",
        f4: "Social",
        f5: "https://linkedin.com",
        img: "https://framerusercontent.com/images/371lVaDSMdqEsHSlTLGeKl7650.webp",
        n1: "3",
    },
    {
        slug: "liam-novak",
        f1: "Liam Novak",
        f2: "Paid ads lead",
        f3: "Manages $4M a year in Meta and Google spend.",
        f4: "Paid ads",
        f5: "https://linkedin.com",
        img: "https://framerusercontent.com/images/NmkpUVq1OjshWo3MRYHXbDUFJGU.webp",
        n1: "4",
    },
    {
        slug: "sofia-marin",
        f1: "Sofia Marín",
        f2: "Content lead",
        f3: "Former magazine editor who writes for search and for people.",
        f4: "Content",
        f5: "https://linkedin.com",
        img: "https://framerusercontent.com/images/wTEJQWR3N9EVhTU88mXAPHBq5g4.webp",
        n1: "5",
    },
    {
        slug: "theo-park",
        f1: "Theo Park",
        f2: "Design lead",
        f3: "Designs the sites, brands and ads our clients launch with.",
        f4: "Design",
        f5: "https://linkedin.com",
        img: "https://framerusercontent.com/images/LBJSHBzWF5iwJGgfJgtazdyk8.webp",
        n1: "6",
    },
]

// reviews — f1 name · f2 role · f3 company · f4 quote · f5 result chip · f6 stars · img avatar
const reviews: CmsRow[] = [
    {
        slug: "r1",
        f1: "Dr. Hannah Lee",
        f2: "Owner",
        f3: "Northside Dental",
        f4: "We went from four new patients a week to four a day. They report every number and explain what they changed.",
        f5: "+826% organic visits",
        f6: "5",
        img: "https://framerusercontent.com/images/YqwmM7lRs3vsXpr2grgwzyJ62LE.webp",
        n1: "1",
    },
    {
        slug: "r2",
        f1: "Marcus Bell",
        f2: "Co-founder",
        f3: "Kinfolk Coffee",
        f4: "Our reels finally look like us. The team shoots, edits and posts, and we just approve.",
        f5: "96k followers",
        f6: "5",
        img: "https://framerusercontent.com/images/YYdQD4OSWKjNOGVWs9tCxMobw8I.webp",
        n1: "2",
    },
    {
        slug: "r3",
        f1: "Priya Nair",
        f2: "Growth lead",
        f3: "Fitloop",
        f4: "The first agency that talks about our margins, not clicks. Ads paid back in eleven days.",
        f5: "6.2× ROAS",
        f6: "5",
        img: "https://framerusercontent.com/images/RqmMNLZRFBKyGJxcMWBx21DI85Q.webp",
        n1: "3",
    },
    {
        slug: "r4",
        f1: "Tom Alvarez",
        f2: "Broker",
        f3: "Haven Realty",
        f4: "Seller leads every week from our own site. We stopped buying leads from portals.",
        f5: "122 leads/mo",
        f6: "5",
        img: "https://framerusercontent.com/images/gv5mT4bQ8T1n4dyt3U0G2Gfwldw.webp",
        n1: "4",
    },
    {
        slug: "r5",
        f1: "Elena Rossi",
        f2: "Founder",
        f3: "Lumen Skin",
        f4: "They built the brand and the launch. We sold out twice in the first month.",
        f5: "$142k launch week",
        f6: "5",
        img: "https://framerusercontent.com/images/FkGV79fUruxxZYYaCa5EOB8RME.webp",
        n1: "5",
    },
    {
        slug: "r6",
        f1: "David Kim",
        f2: "Partner",
        f3: "Orbit Legal",
        f4: "Clients now mention our LinkedIn posts in the first call. That never happened before.",
        f5: "57 consults/mo",
        f6: "5",
        img: "https://framerusercontent.com/images/x1XkAfPNF95aDnEhP091G8c03KY.webp",
        n1: "6",
    },
]

// faq — f1 question · f2 answer · f3 group
const faq: CmsRow[] = [
    {
        slug: "f1",
        f1: "How long until we see results?",
        f2: "Paid ads show results in the first two weeks. Social grows month by month. SEO usually moves in 3 to 6 months, and we show progress in every report.",
        f3: "General",
        n1: "1",
    },
    {
        slug: "f2",
        f1: "Do we have to sign a long contract?",
        f2: "No. Retainers run month to month with 30 days notice. Most clients stay because the numbers keep going up.",
        f3: "General",
        n1: "2",
    },
    {
        slug: "f4",
        f1: "Which industries do you work with?",
        f2: "Local services, e-commerce, apps and professional firms. We say no when we can't move the numbers.",
        f3: "General",
        n1: "4",
    },
    {
        slug: "f5",
        f1: "Who creates the content?",
        f2: "Our in-house team writes, shoots and edits. You approve everything before it goes live.",
        f3: "Process",
        n1: "5",
    },
    {
        slug: "f6",
        f1: "How do you report results?",
        f2: "A live dashboard plus a monthly call where we walk through what worked, what didn't and what we'll change.",
        f3: "Process",
        n1: "6",
    },
    {
        slug: "f7",
        f1: "Can you work with our in-house team?",
        f2: "Yes. We often run one channel while your team handles the rest, and share every file and login.",
        f3: "Process",
        n1: "7",
    },
    {
        slug: "f8",
        f1: "What happens on the first call?",
        f2: "A free 30-minute audit of your site, socials and ads, and a plan you can keep even if we don't work together.",
        f3: "General",
        n1: "8",
    },
]

// posts (blog) — f1 title · f2 category · f3 date · f4 read time · f5 excerpt · f6 body · img cover
const posts: CmsRow[] = [
    {
        slug: "local-seo-2026",
        f1: "Local SEO in 2026: what still moves the map pack",
        f2: "SEO",
        f3: "Sep 18, 2026",
        f4: "7 min",
        f5: "Reviews, pages and links: the three things that still decide who shows up first near you.",
        f6: "Local search still comes down to three things...",
        img: "https://framerusercontent.com/images/pHOBF7LHy4BbDr36flWPxPYRixo.webp",
        n1: "1",
    },
    {
        slug: "reels-that-sell",
        f1: "Reels that sell: the 3-second rule we use for every client",
        f2: "Social media",
        f3: "Sep 04, 2026",
        f4: "5 min",
        f5: "Why the first three seconds decide whether anyone sees the other twenty-seven.",
        f6: "Every reel we make starts with one question...",
        img: "https://framerusercontent.com/images/87wKn5rFSjsCMUA9My0OUYJ4dM.webp",
        n1: "2",
    },
    {
        slug: "roas-is-not-profit",
        f1: "ROAS is not profit: how we report paid ads",
        f2: "Paid ads",
        f3: "Aug 21, 2026",
        f4: "6 min",
        f5: "A 6× return can still lose money. Here is the number we report instead.",
        f6: "Return on ad spend is the number everyone quotes...",
        img: "https://framerusercontent.com/images/NtmyAnUBIcfQXkgdgwQGB2dIVY.webp",
        n1: "3",
    },
    {
        slug: "content-calendar",
        f1: "The one-page content calendar we give every client",
        f2: "Content",
        f3: "Aug 07, 2026",
        f4: "4 min",
        f5: "A plan your team will actually follow, with a template you can copy.",
        f6: "Most content calendars die in week two...",
        img: "https://framerusercontent.com/images/5NYoUMxcMZ7W73IVonEHOzeu5ls.webp",
        n1: "4",
    },
    {
        slug: "landing-pages",
        f1: "Five landing page fixes that doubled conversions",
        f2: "Web design",
        f3: "Jul 24, 2026",
        f4: "6 min",
        f5: "Small changes to headlines, forms and proof that paid for themselves in a week.",
        f6: "Before you spend more on ads...",
        img: "https://framerusercontent.com/images/2JG0A1F7J2tdiUI5Y6YXMfSc.webp",
        n1: "5",
    },
    {
        slug: "agency-or-in-house",
        f1: "Agency or in-house? An honest comparison",
        f2: "Strategy",
        f3: "Jul 10, 2026",
        f4: "8 min",
        f5: "What it really costs to hire a marketing team, and when an agency makes more sense.",
        f6: "It depends on three numbers...",
        img: "https://framerusercontent.com/images/P2vtvmpcIxWwVrN78FW1tzLdNs.webp",
        n1: "6",
    },
]

export const CONTENT: Record<string, CmsRow[]> = {
    site,
    services,
    work,
    team,
    reviews,
    faq,
    posts,
}
